name: main-ci

on:
  push:

jobs:
  main-ci-mono:
    name: Main CI
    timeout-minutes: 5
    runs-on: ubuntu-latest

    env:
      TURBO_URL: ${{ secrets.TURBO_URL }}
      TURBO_CODE: ${{ secrets.TURBO_CODE }}

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.0
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm lint
      - name: format
        run: pnpm format:check
      - name: build
        run: pnpm build:ci
